//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyPC_AutoMusic.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyPC_AutoMusic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加乐谱文件 的本地化字符串。
        /// </summary>
        public static string List_Btn_Add {
            get {
                return ResourceManager.GetString("List_Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除选择的乐谱 的本地化字符串。
        /// </summary>
        public static string List_Btn_Delete {
            get {
                return ResourceManager.GetString("List_Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从文件夹批量导入 的本地化字符串。
        /// </summary>
        public static string List_Btn_ImportFolder {
            get {
                return ResourceManager.GetString("List_Btn_ImportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string List_Btn_Search {
            get {
                return ResourceManager.GetString("List_Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入筛选词 的本地化字符串。
        /// </summary>
        public static string List_FilterTips {
            get {
                return ResourceManager.GetString("List_FilterTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放列表 的本地化字符串。
        /// </summary>
        public static string List_Header_SheetsList {
            get {
                return ResourceManager.GetString("List_Header_SheetsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 乐谱导入失败,请检查乐谱格式是否正确 的本地化字符串。
        /// </summary>
        public static string List_ImportFailure {
            get {
                return ResourceManager.GetString("List_ImportFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以下是导入失败的文件： 的本地化字符串。
        /// </summary>
        public static string List_ImportFailureList {
            get {
                return ResourceManager.GetString("List_ImportFailureList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (目前仅支持导入未加密Json乐谱) 的本地化字符串。
        /// </summary>
        public static string List_ImportFailureTips {
            get {
                return ResourceManager.GetString("List_ImportFailureTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 乐谱导入中，请耐心等待... 的本地化字符串。
        /// </summary>
        public static string List_ImportingFiles {
            get {
                return ResourceManager.GetString("List_ImportingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在导入{0}首乐谱 的本地化字符串。
        /// </summary>
        public static string List_ImportingInBackground {
            get {
                return ResourceManager.GetString("List_ImportingInBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}首乐谱导入成功,{1}首乐谱导入失败 的本地化字符串。
        /// </summary>
        public static string List_ImportResult {
            get {
                return ResourceManager.GetString("List_ImportResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入成功 的本地化字符串。
        /// </summary>
        public static string List_ImportSuccessfully {
            get {
                return ResourceManager.GetString("List_ImportSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择乐谱文件 的本地化字符串。
        /// </summary>
        public static string List_ImportWindowTitle {
            get {
                return ResourceManager.GetString("List_ImportWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你还没有选择乐谱 的本地化字符串。
        /// </summary>
        public static string List_NullDelete {
            get {
                return ResourceManager.GetString("List_NullDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本文件 的本地化字符串。
        /// </summary>
        public static string List_TextFile {
            get {
                return ResourceManager.GetString("List_TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 演奏 的本地化字符串。
        /// </summary>
        public static string Main_Play {
            get {
                return ResourceManager.GetString("Main_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Main_Settings {
            get {
                return ResourceManager.GetString("Main_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 乐谱 的本地化字符串。
        /// </summary>
        public static string Main_Sheets {
            get {
                return ResourceManager.GetString("Main_Sheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SPAM 播放器 的本地化字符串。
        /// </summary>
        public static string Main_WindowTitle {
            get {
                return ResourceManager.GetString("Main_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并连续相同按键 的本地化字符串。
        /// </summary>
        public static string Options_CombineKeys {
            get {
                return ResourceManager.GetString("Options_CombineKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Options_Confirm {
            get {
                return ResourceManager.GetString("Options_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义背景图像 的本地化字符串。
        /// </summary>
        public static string Options_CustomBackground {
            get {
                return ResourceManager.GetString("Options_CustomBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色模式 的本地化字符串。
        /// </summary>
        public static string Options_DarkMode {
            get {
                return ResourceManager.GetString("Options_DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开源地址 的本地化字符串。
        /// </summary>
        public static string Options_GitHub {
            get {
                return ResourceManager.GetString("Options_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string Options_Header_About {
            get {
                return ResourceManager.GetString("Options_Header_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外观 的本地化字符串。
        /// </summary>
        public static string Options_Header_Appearance {
            get {
                return ResourceManager.GetString("Options_Header_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用SkyStudio键位映射 的本地化字符串。
        /// </summary>
        public static string Options_KeyMapper {
            get {
                return ResourceManager.GetString("Options_KeyMapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Options_Language {
            get {
                return ResourceManager.GetString("Options_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台演奏 的本地化字符串。
        /// </summary>
        public static string Options_PlayBackground {
            get {
                return ResourceManager.GetString("Options_PlayBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置文件读取失败，所有设置项已重置为默认值 的本地化字符串。
        /// </summary>
        public static string Options_ReadConfigFailure {
            get {
                return ResourceManager.GetString("Options_ReadConfigFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从设置文件读取路径失败 的本地化字符串。
        /// </summary>
        public static string Options_ReadPathFailure {
            get {
                return ResourceManager.GetString("Options_ReadPathFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题色跟随系统 的本地化字符串。
        /// </summary>
        public static string Options_ThemeColorFollowSystem {
            get {
                return ResourceManager.GetString("Options_ThemeColorFollowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部分乐谱与此功能不兼容，若演奏过程出现意外缺音吞音，请关闭此功能 的本地化字符串。
        /// </summary>
        public static string Options_Tips_CombineKeys {
            get {
                return ResourceManager.GetString("Options_Tips_CombineKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到背景图片，请将bg.jpg(或bg.png)与程序放在同一目录下 的本地化字符串。
        /// </summary>
        public static string Options_Tips_MissBackgroundFile {
            get {
                return ResourceManager.GetString("Options_Tips_MissBackgroundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置项将在程序重启后生效 的本地化字符串。
        /// </summary>
        public static string Options_Tips_RestartApp {
            get {
                return ResourceManager.GetString("Options_Tips_RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经是第一首音乐 的本地化字符串。
        /// </summary>
        public static string Play_AlreadyFirstMusic {
            get {
                return ResourceManager.GetString("Play_AlreadyFirstMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经是最后一首音乐 的本地化字符串。
        /// </summary>
        public static string Play_AlreadyLastMusic {
            get {
                return ResourceManager.GetString("Play_AlreadyLastMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换下一首 的本地化字符串。
        /// </summary>
        public static string Play_Btn_NextMusic {
            get {
                return ResourceManager.GetString("Play_Btn_NextMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换上一首 的本地化字符串。
        /// </summary>
        public static string Play_Btn_PreviousMusic {
            get {
                return ResourceManager.GetString("Play_Btn_PreviousMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到游戏窗口 的本地化字符串。
        /// </summary>
        public static string Play_CantFindWindow {
            get {
                return ResourceManager.GetString("Play_CantFindWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 的本地化字符串。
        /// </summary>
        public static string Play_Info_Author {
            get {
                return ResourceManager.GetString("Play_Info_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 乐谱详情 的本地化字符串。
        /// </summary>
        public static string Play_Info_Header {
            get {
                return ResourceManager.GetString("Play_Info_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲名 的本地化字符串。
        /// </summary>
        public static string Play_Info_Name {
            get {
                return ResourceManager.GetString("Play_Info_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调性 的本地化字符串。
        /// </summary>
        public static string Play_Info_PitchLevel {
            get {
                return ResourceManager.GetString("Play_Info_PitchLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 改编者 的本地化字符串。
        /// </summary>
        public static string Play_Info_TranscribedBy {
            get {
                return ResourceManager.GetString("Play_Info_TranscribedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还没有添加乐谱 的本地化字符串。
        /// </summary>
        public static string Play_MissSheet {
            get {
                return ResourceManager.GetString("Play_MissSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播完暂停 的本地化字符串。
        /// </summary>
        public static string Play_Mode1 {
            get {
                return ResourceManager.GetString("Play_Mode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单曲循环 的本地化字符串。
        /// </summary>
        public static string Play_Mode2 {
            get {
                return ResourceManager.GetString("Play_Mode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顺序播放 的本地化字符串。
        /// </summary>
        public static string Play_Mode3 {
            get {
                return ResourceManager.GetString("Play_Mode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        public static string Play_Pause {
            get {
                return ResourceManager.GetString("Play_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放 的本地化字符串。
        /// </summary>
        public static string Play_Start {
            get {
                return ResourceManager.GetString("Play_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用程序遇到一些问题，该操作已终止，请联系程序开发者反馈此问题 的本地化字符串。
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倍速 的本地化字符串。
        /// </summary>
        public static string Play_SpeedLabel {
            get {
                return ResourceManager.GetString("Play_SpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义键位 的本地化字符串。
        /// </summary>
        public static string Options_CustomKeys {
            get {
                return ResourceManager.GetString("Options_CustomKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 递归导入子文件夹 的本地化字符串。
        /// </summary>
        public static string Options_ImportSubfolders {
            get {
                return ResourceManager.GetString("Options_ImportSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用全局热键 的本地化字符串。
        /// </summary>
        public static string Options_Hotkeys {
            get {
                return ResourceManager.GetString("Options_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 热键：Ctrl+Alt+空格 播放/暂停，Ctrl+Alt+左/右 切换曲目 的本地化字符串。
        /// </summary>
        public static string Options_Tips_Hotkeys {
            get {
                return ResourceManager.GetString("Options_Tips_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义键位 的本地化字符串。
        /// </summary>
        public static string Keybind_Title {
            get {
                return ResourceManager.GetString("Keybind_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击左侧任意一格，然后按下键盘上的按键即可绑定 的本地化字符串。
        /// </summary>
        public static string Keybind_Tips {
            get {
                return ResourceManager.GetString("Keybind_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复默认 的本地化字符串。
        /// </summary>
        public static string Keybind_Reset {
            get {
                return ResourceManager.GetString("Keybind_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该乐谱已加密，暂不支持导入 的本地化字符串。
        /// </summary>
        public static string List_ImportEncrypted {
            get {
                return ResourceManager.GetString("List_ImportEncrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原因 的本地化字符串。
        /// </summary>
        public static string List_ImportFailureReason {
            get {
                return ResourceManager.GetString("List_ImportFailureReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 松开以导入乐谱 的本地化字符串。
        /// </summary>
        public static string List_DropTips {
            get {
                return ResourceManager.GetString("List_DropTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 速度 的本地化字符串。
        /// </summary>
        public static string Play_Info_BPM {
            get {
                return ResourceManager.GetString("Play_Info_BPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时长 的本地化字符串。
        /// </summary>
        public static string Play_Info_Duration {
            get {
                return ResourceManager.GetString("Play_Info_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音符数 的本地化字符串。
        /// </summary>
        public static string Play_Info_Notes {
            get {
                return ResourceManager.GetString("Play_Info_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 市场 的本地化字符串。
        /// </summary>
        public static string Main_Market {
            get {
                return ResourceManager.GetString("Main_Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲谱市场 的本地化字符串。
        /// </summary>
        public static string Market_Header {
            get {
                return ResourceManager.GetString("Market_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新清单 的本地化字符串。
        /// </summary>
        public static string Market_Refresh {
            get {
                return ResourceManager.GetString("Market_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类 的本地化字符串。
        /// </summary>
        public static string Market_Category {
            get {
                return ResourceManager.GetString("Market_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子类 的本地化字符串。
        /// </summary>
        public static string Market_SubCategory {
            get {
                return ResourceManager.GetString("Market_SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string Market_All {
            get {
                return ResourceManager.GetString("Market_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索曲名 的本地化字符串。
        /// </summary>
        public static string Market_SearchHint {
            get {
                return ResourceManager.GetString("Market_SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string Market_Btn_Search {
            get {
                return ResourceManager.GetString("Market_Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载并导入 的本地化字符串。
        /// </summary>
        public static string Market_Download {
            get {
                return ResourceManager.GetString("Market_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载并导入当前列表 的本地化字符串。
        /// </summary>
        public static string Market_DownloadAll {
            get {
                return ResourceManager.GetString("Market_DownloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已下载 的本地化字符串。
        /// </summary>
        public static string Market_Downloaded {
            get {
                return ResourceManager.GetString("Market_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲库 {0} 首 · 更新于 {1} 的本地化字符串。
        /// </summary>
        public static string Market_Status {
            get {
                return ResourceManager.GetString("Market_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还没有曲库清单，点“刷新清单”获取 的本地化字符串。
        /// </summary>
        public static string Market_StatusEmpty {
            get {
                return ResourceManager.GetString("Market_StatusEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在获取曲库清单... 的本地化字符串。
        /// </summary>
        public static string Market_Fetching {
            get {
                return ResourceManager.GetString("Market_Fetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曲库清单获取失败 的本地化字符串。
        /// </summary>
        public static string Market_FetchFailed {
            get {
                return ResourceManager.GetString("Market_FetchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求过于频繁，请在设置中填写 GitHub Token 的本地化字符串。
        /// </summary>
        public static string Market_RateLimit {
            get {
                return ResourceManager.GetString("Market_RateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载 {0}/{1} 的本地化字符串。
        /// </summary>
        public static string Market_Downloading {
            get {
                return ResourceManager.GetString("Market_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已下载并导入 {0} 首 的本地化字符串。
        /// </summary>
        public static string Market_ImportDone {
            get {
                return ResourceManager.GetString("Market_ImportDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有符合条件的曲谱 的本地化字符串。
        /// </summary>
        public static string Market_Empty {
            get {
                return ResourceManager.GetString("Market_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来源仓库 的本地化字符串。
        /// </summary>
        public static string Market_Repo {
            get {
                return ResourceManager.GetString("Market_Repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大小 的本地化字符串。
        /// </summary>
        public static string Market_Col_Size {
            get {
                return ResourceManager.GetString("Market_Col_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GitHub Token（可选） 的本地化字符串。
        /// </summary>
        public static string Options_GitHubToken {
            get {
                return ResourceManager.GetString("Options_GitHubToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于提高市场清单请求限额，留空则为匿名访问 的本地化字符串。
        /// </summary>
        public static string Options_Tips_Token {
            get {
                return ResourceManager.GetString("Options_Tips_Token", resourceCulture);
            }
        }
        
        public static string Humanize_Header {
            get {
                return ResourceManager.GetString("Humanize_Header", resourceCulture);
            }
        }
        
        public static string Humanize_Enable {
            get {
                return ResourceManager.GetString("Humanize_Enable", resourceCulture);
            }
        }
        
        public static string Humanize_Strength {
            get {
                return ResourceManager.GetString("Humanize_Strength", resourceCulture);
            }
        }
        
        public static string Humanize_Seed {
            get {
                return ResourceManager.GetString("Humanize_Seed", resourceCulture);
            }
        }
        
        public static string Humanize_Seed_PerSheet {
            get {
                return ResourceManager.GetString("Humanize_Seed_PerSheet", resourceCulture);
            }
        }
        
        public static string Humanize_Seed_PerPlay {
            get {
                return ResourceManager.GetString("Humanize_Seed_PerPlay", resourceCulture);
            }
        }
        
        public static string Humanize_Jitter {
            get {
                return ResourceManager.GetString("Humanize_Jitter", resourceCulture);
            }
        }
        
        public static string Humanize_JitterMin {
            get {
                return ResourceManager.GetString("Humanize_JitterMin", resourceCulture);
            }
        }
        
        public static string Humanize_JitterMax {
            get {
                return ResourceManager.GetString("Humanize_JitterMax", resourceCulture);
            }
        }
        
        public static string Humanize_JitterMode {
            get {
                return ResourceManager.GetString("Humanize_JitterMode", resourceCulture);
            }
        }
        
        public static string Humanize_JitterExpr {
            get {
                return ResourceManager.GetString("Humanize_JitterExpr", resourceCulture);
            }
        }
        
        public static string Humanize_JitterExprHint {
            get {
                return ResourceManager.GetString("Humanize_JitterExprHint", resourceCulture);
            }
        }
        
        public static string Humanize_Dist_Uniform {
            get {
                return ResourceManager.GetString("Humanize_Dist_Uniform", resourceCulture);
            }
        }
        
        public static string Humanize_Dist_Gaussian {
            get {
                return ResourceManager.GetString("Humanize_Dist_Gaussian", resourceCulture);
            }
        }
        
        public static string Humanize_Dist_Triangular {
            get {
                return ResourceManager.GetString("Humanize_Dist_Triangular", resourceCulture);
            }
        }
        
        public static string Humanize_Dist_Early {
            get {
                return ResourceManager.GetString("Humanize_Dist_Early", resourceCulture);
            }
        }
        
        public static string Humanize_Dist_Late {
            get {
                return ResourceManager.GetString("Humanize_Dist_Late", resourceCulture);
            }
        }
        
        public static string Humanize_Dist_Custom {
            get {
                return ResourceManager.GetString("Humanize_Dist_Custom", resourceCulture);
            }
        }
        
        public static string Humanize_Hold {
            get {
                return ResourceManager.GetString("Humanize_Hold", resourceCulture);
            }
        }
        
        public static string Humanize_HoldMin {
            get {
                return ResourceManager.GetString("Humanize_HoldMin", resourceCulture);
            }
        }
        
        public static string Humanize_HoldMax {
            get {
                return ResourceManager.GetString("Humanize_HoldMax", resourceCulture);
            }
        }
        
        public static string Humanize_Drop {
            get {
                return ResourceManager.GetString("Humanize_Drop", resourceCulture);
            }
        }
        
        public static string Humanize_DropChance {
            get {
                return ResourceManager.GetString("Humanize_DropChance", resourceCulture);
            }
        }
        
        public static string Humanize_Wrong {
            get {
                return ResourceManager.GetString("Humanize_Wrong", resourceCulture);
            }
        }
        
        public static string Humanize_WrongChance {
            get {
                return ResourceManager.GetString("Humanize_WrongChance", resourceCulture);
            }
        }
        
        public static string Humanize_Spread {
            get {
                return ResourceManager.GetString("Humanize_Spread", resourceCulture);
            }
        }
        
        public static string Humanize_SpreadMin {
            get {
                return ResourceManager.GetString("Humanize_SpreadMin", resourceCulture);
            }
        }
        
        public static string Humanize_SpreadMax {
            get {
                return ResourceManager.GetString("Humanize_SpreadMax", resourceCulture);
            }
        }
        
        public static string Humanize_Drift {
            get {
                return ResourceManager.GetString("Humanize_Drift", resourceCulture);
            }
        }
        
        public static string Humanize_DriftMin {
            get {
                return ResourceManager.GetString("Humanize_DriftMin", resourceCulture);
            }
        }
        
        public static string Humanize_DriftMax {
            get {
                return ResourceManager.GetString("Humanize_DriftMax", resourceCulture);
            }
        }
        
        public static string Humanize_Breath {
            get {
                return ResourceManager.GetString("Humanize_Breath", resourceCulture);
            }
        }
        
        public static string Humanize_BreathChance {
            get {
                return ResourceManager.GetString("Humanize_BreathChance", resourceCulture);
            }
        }
        
        public static string Humanize_BreathMin {
            get {
                return ResourceManager.GetString("Humanize_BreathMin", resourceCulture);
            }
        }
        
        public static string Humanize_BreathMax {
            get {
                return ResourceManager.GetString("Humanize_BreathMax", resourceCulture);
            }
        }
        
        public static string Humanize_Fatigue {
            get {
                return ResourceManager.GetString("Humanize_Fatigue", resourceCulture);
            }
        }
        
        public static string Humanize_FatigueStart {
            get {
                return ResourceManager.GetString("Humanize_FatigueStart", resourceCulture);
            }
        }
        
        public static string Humanize_FatigueEnd {
            get {
                return ResourceManager.GetString("Humanize_FatigueEnd", resourceCulture);
            }
        }
        
        public static string Humanize_Grace {
            get {
                return ResourceManager.GetString("Humanize_Grace", resourceCulture);
            }
        }
        
        public static string Humanize_GraceChance {
            get {
                return ResourceManager.GetString("Humanize_GraceChance", resourceCulture);
            }
        }
        
        public static string Humanize_Tips {
            get {
                return ResourceManager.GetString("Humanize_Tips", resourceCulture);
            }
        }
        
        public static string Play_Humanize_Toggle {
            get {
                return ResourceManager.GetString("Play_Humanize_Toggle", resourceCulture);
            }
        }
    }
}
